version: '2'
services:
  database:
    image: postgres:latest
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PWD}
      POSTGRES_DB: ${PGSQL_DB_NAME}
    ports:
      - "5432:5432"

  php:
    build:
      context: ./php-fpm
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    user: ${CURRENT_UID}
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: postgresql://${PGSQL_USER}:${PGSQL_PWD}@database:5432/${PGSQL_DB_NAME}?serverVersion=11&charset=utf8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ../app:/var/www
    ports:
      - 9000:9000
    links:
      - database

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
        - "8080:80"
    links:
      - php
